[general]
# Themes from https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/solarized_light.toml"
]

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[window]
# Start Alacritty in fullscreen by default
# Start Alacritty maximized (z paskiem tytu≈Çu)
startup_mode = "Maximized"
dynamic_title = true
